In [19]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
df= pd.read_csv('..\src\data\postings.csv')

In [10]:
df.shape

(123849, 31)

In [12]:
df.columns

Index(['job_id', 'company_name', 'title', 'description', 'max_salary',
       'pay_period', 'location', 'company_id', 'views', 'med_salary',
       'min_salary', 'formatted_work_type', 'applies', 'original_listed_time',
       'remote_allowed', 'job_posting_url', 'application_url',
       'application_type', 'expiry', 'closed_time',
       'formatted_experience_level', 'skills_desc', 'listed_time',
       'posting_domain', 'sponsored', 'work_type', 'currency',
       'compensation_type', 'normalized_salary', 'zip_code', 'fips'],
      dtype='object')

In [34]:
filtered_df = df[[
    "job_id",
    "title",
    "description",
    "skills_desc",
    "location",
    "remote_allowed",
    "views",
    "applies",
    "listed_time",
    "normalized_salary"
]]

In [35]:
filtered_df

,job_id,title,description,skills_desc,location,remote_allowed,views,applies,listed_time,normalized_salary
0,921716,Marketing Coordinator,Job descriptionA leading real estate firm in N...,Requirements: \n\nWe are seeking a College or ...,"Princeton, NJ",NaN,20.0,2.0,1.713398e+12,38480.0
1,1829192,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",NaN,"Fort Collins, CO",NaN,1.0,NaN,1.712858e+12,83200.0
2,10998357,Assitant Restaurant Manager,The National Exemplar is accepting application...,We are currently accepting resumes for FOH - A...,"Cincinnati, OH",NaN,8.0,NaN,1.713278e+12,55000.0
3,23221523,Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,This position requires a baseline understandin...,"New Hyde Park, NY",NaN,16.0,NaN,1.712896e+12,157500.0
4,35982263,Service Technician,Looking for HVAC service tech with experience ...,NaN,"Burlington, IA",NaN,3.0,NaN,1.713452e+12,70000.0
...,...,...,...,...,...,...,...,...,...,...
123844,3906267117,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,NaN,"Walnut Creek, CA",NaN,1.0,NaN,1.713571e+12,157500.0
123845,3906267126,"Staff Software Engineer, ML Serving Platform",About Pinterest:\n\nMillions of people across ...,NaN,United States,1.0,3.0,NaN,1.713572e+12,NaN
123846,3906267131,"Account Executive, Oregon/Washington",Company Overview\n\nEPS Learning is a leading ...,NaN,"Spokane, WA",1.0,3.0,NaN,1.713572e+12,NaN
123847,3906267195,Business Development Manager,The Business Development Manager is a 'hunter'...,NaN,"Texas, United States",1.0,4.0,NaN,1.713573e+12,NaN
123848,3906267224,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k – $75...,NaN,"San Juan Capistrano, CA",NaN,2.0,NaN,1.713573e+12,72500.0

In [36]:
# Count of missing values
missing = filtered_df.isnull().sum()
missing_pct = (filtered_df.isnull().sum() / len(filtered_df)) * 100

missing_df = pd.DataFrame({
   # 'Missing Count': missing,
    'Missing Percentage': missing_pct
}).sort_values('Missing Percentage', ascending=False)

print(missing_df[missing_df['Missing Percentage'] > 0])

                   Missing Percentage
skills_desc                 98.030666
remote_allowed              87.689848
applies                     81.170619
normalized_salary           70.873402
views                        1.363757
description                  0.005652

In [44]:
filtered_df["skills_desc"].dropna().head(10)

0     Requirements: \n\nWe are seeking a College or ...
2     We are currently accepting resumes for FOH - A...
3     This position requires a baseline understandin...
8     • Requires the ability to communicate effectiv...
9     Knowledge, Skills and Abilities: 1. Proficient...
10    The Production Supervisor must possess strong ...
12    Skills/Qualifications: Two-year or four-year d...
13    Job Overview: Manage a project from start to f...
19    Strong interpersonal communication skills and ...
23    Data Entry Filing Receptionist Duties Customer...
Name: skills_desc, dtype: object

In [45]:
filtered_df.drop(columns=["skills_desc", "remote_allowed"], inplace=True)

C:\Users\Asha\AppData\Local\Temp\ipykernel_12116\563983751.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df.drop(columns=["skills_desc", "remote_allowed"], inplace=True)

In [46]:
filtered_df.shape

(123849, 8)

In [47]:
filtered_df.drop_duplicates(inplace=True)
filtered_df

C:\Users\Asha\AppData\Local\Temp\ipykernel_12116\2034316475.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df.drop_duplicates(inplace=True)

,job_id,title,description,location,views,applies,listed_time,normalized_salary
0,921716,Marketing Coordinator,Job descriptionA leading real estate firm in N...,"Princeton, NJ",20.0,2.0,1.713398e+12,38480.0
1,1829192,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...","Fort Collins, CO",1.0,NaN,1.712858e+12,83200.0
2,10998357,Assitant Restaurant Manager,The National Exemplar is accepting application...,"Cincinnati, OH",8.0,NaN,1.713278e+12,55000.0
3,23221523,Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,"New Hyde Park, NY",16.0,NaN,1.712896e+12,157500.0
4,35982263,Service Technician,Looking for HVAC service tech with experience ...,"Burlington, IA",3.0,NaN,1.713452e+12,70000.0
...,...,...,...,...,...,...,...,...
123844,3906267117,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,"Walnut Creek, CA",1.0,NaN,1.713571e+12,157500.0
123845,3906267126,"Staff Software Engineer, ML Serving Platform",About Pinterest:\n\nMillions of people across ...,United States,3.0,NaN,1.713572e+12,NaN
123846,3906267131,"Account Executive, Oregon/Washington",Company Overview\n\nEPS Learning is a leading ...,"Spokane, WA",3.0,NaN,1.713572e+12,NaN
123847,3906267195,Business Development Manager,The Business Development Manager is a 'hunter'...,"Texas, United States",4.0,NaN,1.713573e+12,NaN
123848,3906267224,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k – $75...,"San Juan Capistrano, CA",2.0,NaN,1.713573e+12,72500.0

In [48]:
filtered_df['job_id'].value_counts()

job_id
921716        1
3903893002    1
3903891958    1
3903891956    1
3903891949    1
             ..
3899522506    1
3899522495    1
3899522457    1
3899522446    1
3906267224    1
Name: count, Length: 123849, dtype: int64

In [49]:
filtered_df.columns

Index(['job_id', 'title', 'description', 'location', 'views', 'applies',
       'listed_time', 'normalized_salary'],
      dtype='object')

Dataset Observations:

The dataset contains multiple metadata, behavioural, and content-related features.

Critical retrieval fields (title, description) show negligible missingness.

Several auxiliary features exhibit high missingness (e.g., skills_desc, remote_allowed, applies).

The following principles guided column selection:

Prioritized features contributing to retrieval relevance, and ranking signals.

Selected Features:

Core Retrieval Signals: title, description

Ranking Signals: views, listed_time

Filtering/Constraints: location

Optional Economic Signal: normalized_salary